### PR TITLE
Drained state added for inactivity handling and bunyan version updated

### LINKED ISSUE #135: [regression] "socket hang up"
We upgraded le_node from 1.3.0 to 1.6.5 (with no other changes) and our node process started crashing every 4 hours with "socket hang up" - with no stack trace unfortunately. We then downgraded le_node back to 1.3.0 and the error went away. So we're 100% sure it's le_node.

This is how we're using le_node:

```
var Logger = require('le_node');
var logger = new Logger({
  token: token,
  bufferSize: 400000,
  secure: true
});

logger.on('error', function(e) {
  console.error(e); // We aren't seeing this in logs.
});

logger.log('info', {
  message: 'message...'
});
```

Given that we're handling the 'error' event, it would seem as though it shouldn't crash. I didn't see in the [full diff](https://github.com/rapid7/le_node/compare/1.3.0...1.6.5?w=1) that immediately jumped out possible regression caused by an unhandled 'error' event.

Is this a known issue? We can try to incrementally upgrade to figure out the exact version that broke, but that will take some time. I was hoping someone here would be able to identify the regression.

### PR DESCRIPTION
**Pull request by stopal-r7**
This should fix #135 and #91.

I was not able to reproduce #127 but this PR may also fix it as it's a high chance that it is related to inactivity timeout handling too. See comment of a user with regards to that: https://github.com/rapid7/le_node/issues/127#issuecomment-247932911

### CODE REVIEW

File: src/logger.js [hunk 1]
```diff
@@ -172,6 +172,21 @@ class Logger extends Writable {
 
     this.on('buffer drain', () => {
       this.debugLogger.log('RingBuffer drained.');
+      this.drained = true;
+    });
+
+    this.on('timed out', () => {
```
Comment (pquinn-r7) [inline src/logger.js]: there is a constant for this timeoutEvent

File: src/logger.js [hunk 2]
```diff
@@ -389,12 +406,6 @@ class Logger extends Writable {
 
         // connection listeners
         connection.on('timeout', () => {
-          // we owe a lot to inactivity timeout handling with regards to clearing
-          // unwanted opened connections hanging around.
-          this.debugLogger.log(
-              `Socket was inactive for ${this.inactivityTimeout / 1000} seconds. Destroying.`);
-          this.closeConnection();
-          this.connection = null;
           this.emit('timed out');
```
Comment (danilosterrapid7) [inline src/logger.js]: If you are going to use the constant up there, use here as well. ;)
